const SIGNIN = {
  SIGNIN_PENDING: 'USER_SIGNIN_PENDING',
  SIGNIN_SUCCESS: 'USER_SIGNIN_SUCCESS',
  SIGNIN_ERROR: 'USER_SIGNIN_ERROR',
  FETCH_USER: 'USER_FETCH_USER',
  FETCH_USER_ERROR: 'USER_FETCH_USER_ERROR',
};

export default SIGNIN;
